# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         UltraDNS
version:      0.04
version_from: lib/UltraDNS.pm
installdirs:  site
requires:
    Net::SSLeay:                   1.35
    RPC::XML:                      0.64
    Test::Exception:               0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
